# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f4ebd66b9ef17ff3dc0f7ce1bfeac8fbac3139406915b82a2d84404366fd7cea6c79204c0a19e9d3bee8f6d680c188812519c5652e37dd04a36c8471e16a71

test:
  secret_key_base: bf34cf38715ad7562a116447feb59848c1a751d7e3207bb053b277681e875ec6099c3c098c800b0c8c74acd3130f18acf75133aa5047bab6f36a806bb41edd32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
